# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssh_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ssh_service.proto\x12\x0bssh_service\"M\n\x11RunCommandRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"3\n\x12RunCommandResponse\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\t\"B\n\x17RemoveConnectionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x02 \x01(\t\"*\n\x18RemoveConnectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc4\x01\n\nSshService\x12S\n\nRunCommand\x12\x1e.ssh_service.RunCommandRequest\x1a\x1f.ssh_service.RunCommandResponse\"\x00(\x01\x30\x01\x12\x61\n\x10RemoveConnection\x12$.ssh_service.RemoveConnectionRequest\x1a%.ssh_service.RemoveConnectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssh_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RUNCOMMANDREQUEST']._serialized_start=34
  _globals['_RUNCOMMANDREQUEST']._serialized_end=111
  _globals['_RUNCOMMANDRESPONSE']._serialized_start=113
  _globals['_RUNCOMMANDRESPONSE']._serialized_end=164
  _globals['_REMOVECONNECTIONREQUEST']._serialized_start=166
  _globals['_REMOVECONNECTIONREQUEST']._serialized_end=232
  _globals['_REMOVECONNECTIONRESPONSE']._serialized_start=234
  _globals['_REMOVECONNECTIONRESPONSE']._serialized_end=276
  _globals['_SSHSERVICE']._serialized_start=279
  _globals['_SSHSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
