# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ssh_service_pb2 as ssh__service__pb2


class SshServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCommand = channel.stream_stream(
                '/ssh_service.SshService/RunCommand',
                request_serializer=ssh__service__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=ssh__service__pb2.RunCommandResponse.FromString,
                )
        self.RemoveConnection = channel.unary_unary(
                '/ssh_service.SshService/RemoveConnection',
                request_serializer=ssh__service__pb2.RemoveConnectionRequest.SerializeToString,
                response_deserializer=ssh__service__pb2.RemoveConnectionResponse.FromString,
                )


class SshServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunCommand(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCommand': grpc.stream_stream_rpc_method_handler(
                    servicer.RunCommand,
                    request_deserializer=ssh__service__pb2.RunCommandRequest.FromString,
                    response_serializer=ssh__service__pb2.RunCommandResponse.SerializeToString,
            ),
            'RemoveConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveConnection,
                    request_deserializer=ssh__service__pb2.RemoveConnectionRequest.FromString,
                    response_serializer=ssh__service__pb2.RemoveConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssh_service.SshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SshService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunCommand(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ssh_service.SshService/RunCommand',
            ssh__service__pb2.RunCommandRequest.SerializeToString,
            ssh__service__pb2.RunCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ssh_service.SshService/RemoveConnection',
            ssh__service__pb2.RemoveConnectionRequest.SerializeToString,
            ssh__service__pb2.RemoveConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
